language: node_js

node_js:
    - "10"

notifications:
    email:
      recipients:
        - filters@adguard.com
      on_success: never
      on_failure: always

install:
    - npm install

script:
    - node index.js
