language: bash

node_js:
    - "9.5"

notifications:
    email:
      recipients:
        - filters@adguard.com
      on_success: never
      on_failure: always

install:
    - npm install

script:
    - node index.js

deploy:
    - edge:
        branch: v1.8.47

    - provider: pages
      skip-cleanup: true
      local-dir: platforms
      github-token: $GITHUB_TOKEN
      verbose: true
      on:
        branch: master

after_deploy:
    - /bin/bash push.sh
